config/routes.rb
Rails.application.routes.draw do
   
  get 'sessions/login'
  get 'sessions/register'
  get 'sessions/logout'
  post '/login', to: 'sessions#login_user' 
  post '/users', to: 'sessions#create_new_user'
  root 'dogs#index'
  resources :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_one_attached :avatar
  validates :name, :motto, :avatar, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to sessions_login_path unless current_user
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  def index
    @dogs = Dog.all.order("created_at DESC")
  end

  def show
  end

  def new
    @dog = Dog.new
  end

  def edit
  end

  def destroy
    @dog.destroy  
    redirect_to dogs_path
  end

  def create  
    dog = Dog.create(dog_params).blank?
    redirect_to dogs_path
  end

  def update
    @dog.update(dog_params)
    redirect_to dog_path(@dog)
  end

  private 

  def set_dog 
    @dog = Dog.find(params[:id])
  end

  def dog_params
    params.require(:dog).permit(:name, :motto, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def register
  end

  def login_user
    user = User.find_by_email(params[:email])
    #if the user exist and the password entered is correct
    if user && user.authenticate(params[:password])
      #save the user id inside the browser cookie.
      #login in when they navigate around the browser
      session[:user_id] = user.id 
      redirect_to root_path
    else 
    #if user's login doesn't work, send them back to the login
      redirect_to sessions_login_path
    end
  end

  def logout
    session[:user_id] = nil 
    redirect_to sessions_login_path
  end

  def create_new_user
    user = User.create(user_params)
    if user.save 
      session[:user_id] = user.id
      redirect_to root_path
    else  
      redirect_to sessions_register_path
    end
  end

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dogs/edit.html.erb
<div class="container">
<div class="segment-group">
  <div class="segment">
    <%= form_with model: @dog do |form| %>
      <div class="segment-input">
        <%= form.text_field :name, placeholder: "Name"%>
      </div>
      <div class="segment-input">
        <%= form.text_field :motto, placeholder: "Motto"%>
      </div>
      <div class="segment-input">
        <%= form.file_field :avatar, placeholder: "Upload photo", class: "inputfile" %>
        <%= form.label "Choose a file", for: "dog_avatar" %>
      </div> 
      <div class="segment-button-group">  
        <%= form.submit "Edit", class: "button-control" %>  
      </div>
    <% end %>
  </div>
 <div class="segment-compact">
    <div class="segment-image"> 
        <% if @dog.avatar.attached? %>
          <img src="<%=(url_for(@dog.avatar))%>" >
        <% end %>
      </div>
  </div>
</div>
</div>

app/views/dogs/index.html.erb
<div class="container">
  <div class="card-group">
  <% @dogs.each do |dog| %>
     <div class="card">
        <div class="card-header"><%= dog.name %></div>
         <div class="card-image"> 
           <% if dog.avatar.attached? %>
            <%= link_to dog_path(dog), method: 'get' do %>
              <img src="<%=(url_for(dog.avatar))%>" >
            <% end %>
           
          <% end %>

         </div>
         <div class="card-footer">
          <button class="card-button"> <%= link_to 'Show', dog_path(dog), method: 'get' %></button>
          <button class="card-button"><%= link_to 'Edit', edit_dog_path(dog), method: 'get'%></button>
          <button class="card-button">  <%= link_to 'Remove', dog_path(dog), method: 'delete', 
              data: { confirm: 'Are you sure?' }%></button>
         </div> 
       </div>
  <% end %>
</div>
</div>

app/views/dogs/new.html.erb
  <div class="container">
  <div class="segment-group">
    <div class="segment">
      <%= form_with model: @dog do |form| %>
        <div class="segment-input">
          <%= form.text_field :name, placeholder: "Name", required: true %>
        </div>
        <div class="segment-input">
          <%= form.text_field :motto, placeholder: "Motto", required: true %>
        </div>
        <div class="segment-input">
          <%= form.file_field :avatar, placeholder: "Upload photo", class: "inputfile" , required: true %>
          <%= form.label "Choose a file", for: "dog_avatar" %>
        </div> 
        <div class="segment-button-group">  
          <%= form.submit "Create dog", class: "button-control", id: "create-dog", disabled:true %>  
        </div>
      <% end %>
    </div>
    <div class="segment-compact" id="segment-preview-image" hidden>
      <div class="segment-image">
        <img id="preview-image">
      </div>
    </div>

  </div>
  </div>

app/views/dogs/show.html.erb
<div class="container">
<div class="segment-group">
  <div class="segment">
      <div class="segment-label"><b>Name: </b><%= @dog.name %></div>
      <div class="segment-label"><b>Motto: </b><%= @dog.motto %></div>
      
      <div class="segment-button-group">
         <button class="button-control"><%= link_to 'Edit', edit_dog_path(@dog), method: 'get'%></button>
         <button class="button-control"><%= link_to 'Remove', dog_path(@dog), method: 'delete', data: { confirm: 'Are you sure?' }%></button>   
      </div>
  </div>
  <div class="segment-compact-show">
    <div class="segment-image"> 
           <% if @dog.avatar.attached? %>
              <img src="<%=(url_for(@dog.avatar))%>" >
          <% end %>
      </div>
  </div>
</div>
</div>

app/views/layouts/_navbar.html.erb
 <nav class="navbar">
    <div class="navbar-brand"> Dog Shop</div>
   <% if current_user %>
     <div class="navbar-item">
     
      <%= link_to "Home", root_path, class: "button-control"  %>
     </div>
     <div class="navbar-item">
      <%= link_to "Add New", new_dog_path , class: "button-control" , id: "add-new"%> 
     </div>  
     <div class="navbar-item">
       <%= current_user.name %>
     </div>
     <div class="navbar-item">
      <%= link_to "Logout", sessions_logout_path, class: "button-control" %>
     </div>
   <% else %>
      <div class="navbar-item">
        <%= link_to "Login", sessions_login_path, class: "button-control" %>
      </div>
       <div class="navbar-item">
        <%= link_to "Register", sessions_register_path, class: "button-control" %>
      </div>
   <% end %> 
   
    
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dog App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>
<%=  %>